server-name=Bedrock Network | Survival
gamemode=survival
force-gamemode=false
difficulty=normal
allow-cheats=false
max-players=20
online-mode=true
allow-list=true
server-port=19133
server-portv6=19153
enable-lan-visibility=false
view-distance=12
tick-distance=6
player-idle-timeout=0
max-threads=0
level-name=SurvivalWorld
level-seed=
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=true
compression-threshold=1
compression-algorithm=zlib
chat-restriction=None
disable-player-interaction=false
client-side-chunk-generation-enabled=true
block-network-ids-are-hashes=true
disable-custom-skins=false
server-build-radius-ratio=Disabled
