server-name=Bedrock Network | BedWars
gamemode=adventure
force-gamemode=true
difficulty=normal
allow-cheats=true
max-players=8
online-mode=true
allow-list=false
server-port=19135
server-portv6=19155
enable-lan-visibility=false
view-distance=10
tick-distance=4
player-idle-timeout=0
max-threads=0
# SilentBedwars upstream abre explícitamente el nivel "world".
level-name=world
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=true
