server-name=Bedrock Network | SkyWars
gamemode=adventure
force-gamemode=true
difficulty=normal
allow-cheats=true
max-players=20
online-mode=true
allow-list=false
server-port=19136
server-portv6=19156
enable-lan-visibility=false
view-distance=10
tick-distance=4
player-idle-timeout=0
max-threads=0
level-name=SkyWars
default-player-permission-level=member
texturepack-required=false
content-log-file-enabled=true
